### ISSUE TITLE
Uncaught SyntaxError: Identifier 'global' has already been declared" error

### ISSUE THREAD

**Issue by Almerxsese** [leungwensen/zero-lang#2]
"Uncaught SyntaxError: Identifier 'global' has already been declared" error

This error is raised when I do a require of 'xmind' module (which has zero-lang within its node-modules)
The error is raised both if I require from 'main' or 'renderer' process

Best regards
Michel Kern

**Comment by leungwensen** [comment]
@Almerxsese , is it used in an electron-based project?

**Comment by leungwensen** [comment]
@Almerxsese please update to [xmind@0.4.0](https://www.npmjs.com/package/xmind) and have a try.

thank you very much for reporting this bug!

**Comment by Almerxsese** [comment]
Hi

Yes I noticed the error in an Electron based project
The proposed Fix (please update to xmind@0.4.0) is OK !!
Thanks a lot for the Quick and effective Fix

Best Regards
Michel Kern
